# Import Libaries

In [79]:
import numpy as np
import pandas as pd

# Importing Data

In [80]:
crop = pd.read_csv("Crop_recommendation.csv")
crop.head()

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

# Asq Six Question to yourself

In [81]:
crop.shape

(2200, 8)

In [82]:
crop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   N            2200 non-null   int64  
 1   P            2200 non-null   int64  
 2   K            2200 non-null   int64  
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object 
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB


In [83]:
crop.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [84]:
crop.duplicated().sum()

0

In [85]:
crop.describe()

N            P            K  temperature     humidity  \
count  2200.000000  2200.000000  2200.000000  2200.000000  2200.000000   
mean     50.551818    53.362727    48.149091    25.616244    71.481779   
std      36.917334    32.985883    50.647931     5.063749    22.263812   
min       0.000000     5.000000     5.000000     8.825675    14.258040   
25%      21.000000    28.000000    20.000000    22.769375    60.261953   
50%      37.000000    51.000000    32.000000    25.598693    80.473146   
75%      84.250000    68.000000    49.000000    28.561654    89.948771   
max     140.000000   145.000000   205.000000    43.675493    99.981876   

                ph     rainfall  
count  2200.000000  2200.000000  
mean      6.469480   103.463655  
std       0.773938    54.958389  
min       3.504752    20.211267  
25%       5.971693    64.551686  
50%       6.425045    94.867624  
75%       6.923643   124.267508  
max       9.935091   298.560117

In [86]:
crop['label'].value_counts()

label
rice           100
maize          100
jute           100
cotton         100
coconut        100
papaya         100
orange         100
apple          100
muskmelon      100
watermelon     100
grapes         100
mango          100
banana         100
pomegranate    100
lentil         100
blackgram      100
mungbean       100
mothbeans      100
pigeonpeas     100
kidneybeans    100
chickpea       100
coffee         100
Name: count, dtype: int64

# Encoding

In [87]:
crop_dict = {
    'rice': 1,
    'maize': 2,
    'jute': 3,
    'cotton': 4,
    'coconut': 5,
    'papaya': 6,
    'orange': 7,
    'apple': 8,
    'muskmelon': 9,
    'watermelon': 10,
    'grapes': 11,
    'mango': 12,
    'banana': 13,
    'pomegranate': 14,
    'lentil': 15,
    'blackgram': 16,
    'mungbean': 17,
    'mothbeans': 18,
    'pigeonpeas': 19,
    'kidneybeans': 20,
    'chickpea': 21,
    'coffee': 22
}
crop['crop_num']=  crop['label'].map(crop_dict)

In [88]:
crop

N   P   K  temperature   humidity        ph    rainfall   label  \
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice   
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice   
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice   
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice   
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice   
...   ...  ..  ..          ...        ...       ...         ...     ...   
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee   
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee   
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee   
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee   
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee   

      crop_num  
0            1  
1            1  
2            1  
3            1  
4            1  
...        ...  
2195        22  
2196        22  
2197        22  
2198        22  
2199        22  

[2200 rows x 9 columns]

In [89]:
crop.drop(['label'],axis=1,inplace=True)
crop.head()

N   P   K  temperature   humidity        ph    rainfall  crop_num
0  90  42  43    20.879744  82.002744  6.502985  202.935536         1
1  85  58  41    21.770462  80.319644  7.038096  226.655537         1
2  60  55  44    23.004459  82.320763  7.840207  263.964248         1
3  74  35  40    26.491096  80.158363  6.980401  242.864034         1
4  78  42  42    20.130175  81.604873  7.628473  262.717340         1

In [90]:
type(crop)


pandas.core.frame.DataFrame

In [91]:
# Data Preprocessing - Remove invalid values
df_cleaned = crop.dropna()
df_cleaned = df_cleaned[(df_cleaned['N'] > 0) & (df_cleaned['P'] > 0) & 
                        (df_cleaned['K'] > 0) & (df_cleaned['temperature'] > 0) & 
                        (df_cleaned['humidity'] > 0) & (df_cleaned['ph'] > 0) & 
                        (df_cleaned['rainfall'] > 0)]

# Reset the index
df_cleaned.reset_index(drop=True, inplace=True)


# Train Test Split

In [92]:
print(df_cleaned.columns)


Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'crop_num'], dtype='object')


In [93]:
# Split the cleaned data into features (X) and target (y)
X = df_cleaned.drop(['crop_num'], axis=1)  # Feature columns
y = df_cleaned['crop_num']  # Target column


In [94]:
X

N   P   K  temperature   humidity        ph    rainfall
0      90  42  43    20.879744  82.002744  6.502985  202.935536
1      85  58  41    21.770462  80.319644  7.038096  226.655537
2      60  55  44    23.004459  82.320763  7.840207  263.964248
3      74  35  40    26.491096  80.158363  6.980401  242.864034
4      78  42  42    20.130175  81.604873  7.628473  262.717340
...   ...  ..  ..          ...        ...       ...         ...
2168  107  34  32    26.774637  66.413269  6.780064  177.774507
2169   99  15  27    27.417112  56.636362  6.086922  127.924610
2170  118  33  30    24.131797  67.225123  6.362608  173.322839
2171  117  32  34    26.272418  52.127394  6.758793  127.175293
2172  104  18  30    23.603016  60.396475  6.779833  140.937041

[2173 rows x 7 columns]

In [95]:
y

0        1
1        1
2        1
3        1
4        1
        ..
2168    22
2169    22
2170    22
2171    22
2172    22
Name: crop_num, Length: 2173, dtype: int64

In [96]:
y.shape

(2173,)

In [97]:
from sklearn.model_selection import train_test_split

In [98]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [99]:
X_train

N   P   K  temperature   humidity        ph    rainfall
1477  99   6  46    28.614751  94.222530  6.396379   28.985742
555   35  57  25    27.095629  42.262062  8.340398   71.127104
1472  99  29  55    29.193787  91.462411  6.660955   26.482403
450   17  67  18    31.219275  56.468689  5.611511  129.202865
590   35  52  15    28.698413  61.147544  9.935091   65.675918
...   ..  ..  ..          ...        ...       ...         ...
1638  12   6   8    30.848350  92.867737  6.388617  107.414268
1095  11  36  33    35.990097  52.227805  5.978634   95.371348
1130   5  32  33    32.323622  52.589677  5.842764   93.367188
1294  83  25  53    26.491953  80.046782  6.057697   57.727992
860   36  67  20    20.390783  60.475289  6.924042   53.315086

[1738 rows x 7 columns]


# Scale the features using MinMaxScaler

In [100]:
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler()

X_train = ms.fit_transform(X_train)
X_test = ms.transform(X_test)

In [101]:
X_train

array([[0.70503597, 0.00714286, 0.205     , ..., 0.93294268, 0.44968493,
        0.0315233 ],
       [0.24460432, 0.37142857, 0.1       , ..., 0.3266063 , 0.75200486,
        0.18292095],
       [0.70503597, 0.17142857, 0.25      , ..., 0.90073433, 0.49082992,
        0.02252977],
       ...,
       [0.02877698, 0.19285714, 0.14      , ..., 0.44712117, 0.36359073,
        0.26282099],
       [0.58992806, 0.14285714, 0.24      , ..., 0.76752323, 0.39701562,
        0.13478311],
       [0.25179856, 0.44285714, 0.075     , ..., 0.53913984, 0.53174341,
        0.11892924]])

# Training Models

In [102]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier, ExtraTreeClassifier
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
import pandas as pd
import numpy as np

# Assuming the dataset `crop` is loaded
# Replace this with your actual data loading process if needed
# For example: crop = pd.read_csv("your_file.csv")

# Step 1: Separate features (X) and target (y)
X = crop[['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall']]  # Features
y = crop['crop_num']  # Target variable

# Step 2: Handle missing values
# Remove rows with NaN in the target column since these can't be used for training
X = X[~y.isna()]
y = y[~y.isna()]

# Ensure the target variable is integer
y = y.astype(int)

# Step 3: Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 4: Feature scaling using MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)  # Scale training data
X_test = scaler.transform(X_test)  # Scale test data based on training parameters

# Step 5: Define models
models = {
    'Logistic Regression': LogisticRegression(),
    'Naive Bayes': GaussianNB(),
    'Support Vector Machine': SVC(),
    'K-Nearest Neighbors': KNeighborsClassifier(),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Bagging': BaggingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'Extra Trees': ExtraTreeClassifier(),
}

# Step 6: Train and evaluate each model
for name, model in models.items():
    model.fit(X_train, y_train)  # Train the model
    y_pred = model.predict(X_test)  # Predict on test set
    
    # Print evaluation metrics
    print(f"{name} with Accuracy: {accuracy_score(y_test, y_pred):.4f}")
    print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}")
    print("=" * 60)

    

Logistic Regression with Accuracy: 0.9182
Confusion Matrix:
[[16  0  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 6  0 16  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1]
 [ 0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 27  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  3  0  0  0  0  0]
 [ 0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 23  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 23

/home/jyoti/myenv/lib/python3.12/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoost with Accuracy: 0.0955
Confusion Matrix:
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 21  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 23  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 17  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 27  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 23  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 14  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 23  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 21  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 23  0  0  

In [103]:
# finally selected randomforest model

rfc = RandomForestClassifier()
rfc.fit(X_train,y_train)
ypred = rfc.predict(X_test)
accuracy_score(y_test,ypred)

0.9931818181818182

In [104]:
# or gausianjb
gnb = GaussianNB()
gnb.fit(X_train,y_train)
ypred = gnb.predict(X_test)
accuracy_score(y_test,ypred)

0.9954545454545455

In [105]:
# Make predictions on the test set
predictions = model.predict(X_test)

# Function to filter predictions
def filter_predictions(predictions):
    valid_crops = set([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0])
    return [pred if pred in valid_crops else 'Not_possible' for pred in predictions]

# Apply the filter to predictions
filtered_predictions = filter_predictions(predictions)


In [106]:
from sklearn.metrics import classification_report, accuracy_score

# Calculate and print the accuracy and classification report
accuracy = accuracy_score(y_test, filtered_predictions)
print(f"Accuracy: {accuracy}")
print("Classification Report:")
print(classification_report(y_test, filtered_predictions))


Accuracy: 0.925
Classification Report:
              precision    recall  f1-score   support

           1       0.65      0.79      0.71        19
           2       0.90      0.90      0.90        21
           3       0.68      0.57      0.62        23
           4       0.94      0.88      0.91        17
           5       1.00      0.96      0.98        27
           6       0.92      0.96      0.94        23
           7       1.00      1.00      1.00        14
           8       1.00      1.00      1.00        23
           9       0.89      0.94      0.91        17
          10       1.00      0.89      0.94        19
          11       1.00      1.00      1.00        14
          12       1.00      1.00      1.00        19
          13       1.00      1.00      1.00        21
          14       0.96      1.00      0.98        23
          15       0.73      1.00      0.85        11
          16       0.89      0.80      0.84        20
          17       1.00      1.00      1.0

# Predictive System

In [107]:
import pickle

# Saving the trained RandomForest model and MinMaxScaler
pickle.dump(rfc, open('model.pkl', 'wb'))
pickle.dump(ms, open('minmaxscaler.pkl', 'wb'))


In [108]:
import pickle

# Load the saved RandomForest model and MinMaxScaler
rfc = pickle.load(open('model.pkl', 'rb'))
ms = pickle.load(open('minmaxscaler.pkl', 'rb'))


In [109]:
def validate_inputs(N, P, K, temperature, humidity, ph, rainfall):
    # Check if any input value is less than or equal to zero
    if N <= 0 or P <= 0 or K <= 0 or temperature <= 0 or humidity <= 0 or ph <= 0 or rainfall <= 0:
        raise ValueError("Input values must be greater than zero and realistic.")
    
    # Optional: Check if the values are too high to be realistic (you can adjust the limits)
    if N > 150 or P > 150 or K > 150 or temperature > 50 or humidity > 100 or ph > 9 or rainfall > 300:
        raise ValueError("Input values are too high and unrealistic.")
    
    return True


In [110]:
import numpy as np

def recommendation(N, P, K, temperature, humidity, ph, rainfall):
    try:
        # Step 1: Validate inputs
        validate_inputs(N, P, K, temperature, humidity, ph, rainfall)

        # Step 2: Prepare the input features for prediction
        features = np.array([[N, P, K, temperature, humidity, ph, rainfall]])

        # Step 3: Scale the features using the saved MinMaxScaler
        transformed_features = ms.transform(features)

        # Step 4: Get the prediction using the RandomForest model
        prediction = rfc.predict(transformed_features)
        prediction_proba = rfc.predict_proba(transformed_features)

        # Step 5: Check prediction probability for confidence
        max_prob = max(prediction_proba[0])
        if max_prob < 0.2:  # Threshold for uncertainty
            return "Not_possible"  # If model is uncertain, return a message

        # Step 6: Return the predicted crop
        return prediction[0]

    except ValueError as ve:
        return f"Error: {ve}"  # Handle invalid inputs gracefully




In [111]:
# new inputs


N = 40
P = 50
k = 50
temperature = 40.0
humidity = 20
ph = 100
rainfall = 100

predict = recommendation(N,P,k,temperature,humidity,ph,rainfall)

crop_dict = {1: "Rice", 2: "Maize", 3: "Jute", 4: "Cotton", 5: "Coconut", 6: "Papaya", 7: "Orange",
                 8: "Apple", 9: "Muskmelon", 10: "Watermelon", 11: "Grapes", 12: "Mango", 13: "Banana",
                 14: "Pomegranate", 15: "Lentil", 16: "Blackgram", 17: "Mungbean", 18: "Mothbeans",
                 19: "Pigeonpeas", 20: "Kidneybeans", 21: "Chickpea", 22: "Coffee"}

if predict in crop_dict:
    crop = crop_dict[predict]
    print("{} is a best crop to be cultivated ".format(crop))
else:
    print("Sorry are not able to recommend a proper crop for this environment")

Sorry are not able to recommend a proper crop for this environment


In [112]:
# new inputs 2


N = 100
P = 90
k = 100
temperature = 50.0
humidity = 90.0
ph = 100
rainfall = 202.0

predict = recommendation(N,P,k,temperature,humidity,ph,rainfall)

crop_dict = {1: "Rice", 2: "Maize", 3: "Jute", 4: "Cotton", 5: "Coconut", 6: "Papaya", 7: "Orange",
                 8: "Apple", 9: "Muskmelon", 10: "Watermelon", 11: "Grapes", 12: "Mango", 13: "Banana",
                 14: "Pomegranate", 15: "Lentil", 16: "Blackgram", 17: "Mungbean", 18: "Mothbeans",
                 19: "Pigeonpeas", 20: "Kidneybeans", 21: "Chickpea", 22: "Coffee"}

if predict in crop_dict:
    crop = crop_dict[predict]
    print("{} is a best crop to be cultivated ".format(crop))
else:
    print("Sorry are not able to recommend a proper crop for this environment")

Sorry are not able to recommend a proper crop for this environment


In [113]:
# new inputs 2
N = 10
P = 10
k = 10
temperature = 15.0
humidity = 80.0
ph = 4.5
rainfall = 10.0

predict = recommendation(N,P,k,temperature,humidity,ph,rainfall)

crop_dict = {1: "Rice", 2: "Maize", 3: "Jute", 4: "Cotton", 5: "Coconut", 6: "Papaya", 7: "Orange",
                 8: "Apple", 9: "Muskmelon", 10: "Watermelon", 11: "Grapes", 12: "Mango", 13: "Banana",
                 14: "Pomegranate", 15: "Lentil", 16: "Blackgram", 17: "Mungbean", 18: "Mothbeans",
                 19: "Pigeonpeas", 20: "Kidneybeans", 21: "Chickpea", 22: "Coffee"}

if predict in crop_dict:
    crop = crop_dict[predict]
    print("{} is a best crop to be cultivated ".format(crop))
else:
    print("Sorry are not able to recommend a proper crop for this environment")

Orange is a best crop to be cultivated 


/home/jyoti/myenv/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
